name: CI/CD using github actions & docker

# event trigger
# mainì´ë‚˜ develop ë¸Œëœì¹˜ì— pushê°€ ë˜ì—ˆì„ ë•Œ ì‹¤í–‰
on:
  push:
    branches: ["main", "develop"]

permissions:
  contents: read

jobs:
  CI-CD:
    runs-on: ubuntu-latest
    steps:
      # JDK setting - github actionsì—ì„œ ì‚¬ìš©í•  JDK ì„¤ì • (í”„ë¡œì íŠ¸ë‚˜ AWSì˜ java ë²„ì „ê³¼ ë‹¬ë¼ë„ ë¬´ë°©)
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      # í™˜ê²½ë³„ yml íŒŒì¼ ìƒì„±(1) - application.yml
      - name: make application.yml
        if: |
          contains(github.ref, 'main') ||
          contains(github.ref, 'develop')
        run: |
          cd library
          mkdir ./src/main/resources # resources í´ë” ìƒì„±
          cd ./src/main/resources # resources í´ë”ë¡œ ì´ë™
          touch ./application.yml # application.yml ìƒì„±
          echo "${{ secrets.YML }}" > ./application.yml # github actionsì—ì„œ ì„¤ì •í•œ ê°’ì„ application.yml íŒŒì¼ì— ì“°ê¸°
        shell: bash

      # í™˜ê²½ë³„ yml íŒŒì¼ ìƒì„±(2) - dev
      - name: make application-dev.yml
        if: contains(github.ref, 'develop')
        run: |
          cd library
          cd ./src/main/resources
          touch ./application-dev.yml
          echo "${{ secrets.YML_DEV }}" > ./application-dev.yml
        shell: bash

      # í™˜ê²½ë³„ yml íŒŒì¼ ìƒì„±(3) - prod
      - name: make application-prod.yml
        if: contains(github.ref, 'main')
        run: |
          cd library
          cd ./src/main/resources
          touch ./application-prod.yml
          echo "${{ secrets.YML_PROD }}" > ./application-prod.yml
        shell: bash

      # run test code
      - name: Run Tests with Gradle
        run: |
          cd /home/runner/work/library/library/library
          chmod +x gradlew
          ./gradlew test

      # gradle build test
      - name: Build with Gradle
        run: |
          cd /home/runner/work/library/library/library
          chmod +x gradlew
          ./gradlew build -x test

      # docker build & push to production
      - name: Docker build & push to prod
        if: contains(github.ref, 'main')
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -f Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/library-prod .
          docker push ${{ secrets.DOCKER_USERNAME }}/library-prod

      # docker build & push to develop
      - name: Docker build & push to dev
        if: contains(github.ref, 'develop')
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -f Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/library-dev .
          docker push ${{ secrets.DOCKER_USERNAME }}/library-dev

      ## deploy to production
      - name: Deploy to prod
        uses: appleboy/ssh-action@master
        id: deploy-prod
        if: contains(github.ref, 'main')
        with:
          host: ${{ secrets.PROD_HOST_IP }} # EC2 í¼ë¸”ë¦­ IPv4 DNS
          username: ubuntu
          port: 22
          key: ${{ secrets.PEM_KEY }}
          script: |
            cd Library
            docker compose stop backend
            docker compose rm -f backend
            docker pull ${{ secrets.DOCKER_USERNAME }}/library-prod
            docker compose up -d backend
            docker image prune -f

            # âœ… Health Check (ë°°í¬ í›„ API ì •ìƒ ì‘ë™ ì—¬ë¶€ í™•ì¸)
            echo "Waiting for API to start..."
            sleep 10  # APIê°€ ì‹œì‘ë  ì‹œê°„ì„ ì£¼ê¸° ìœ„í•´ 10ì´ˆ ëŒ€ê¸°
            RESPONSE_CODE=$(curl -o /dev/null -s -w "%{http_code}" http://backend:8080/health)
            if [ "$RESPONSE_CODE" -ne 200 ]; then
              echo "ğŸš¨ API Health Check Failed! Response Code: $RESPONSE_CODE"
              exit 1
            else
              echo "âœ… API Health Check Passed! Service is running."
            fi

      ## deploy to develop
      - name: Deploy to dev
        uses: appleboy/ssh-action@master
        id: deploy-dev
        if: contains(github.ref, 'develop')
        with:
          host: ${{ secrets.DEV_HOST_IP }} # EC2 í¼ë¸”ë¦­ IPv4 DNS
          username: ubuntu
          password: ${{ secrets.PASSWORD }}
          port: 22
          key: ${{ secrets.PEM_KEY }}
          script: |
            cd Library
            docker compose stop backend
            docker compose rm -f backend
            docker pull ${{ secrets.DOCKER_USERNAME }}/library-dev
            docker compose up -d backend
            docker image prune -f

            # âœ… Health Check (ë°°í¬ í›„ API ì •ìƒ ì‘ë™ ì—¬ë¶€ í™•ì¸)
            echo "Waiting for API to start..."
            sleep 10  # APIê°€ ì‹œì‘ë  ì‹œê°„ì„ ì£¼ê¸° ìœ„í•´ 10ì´ˆ ëŒ€ê¸°
            RESPONSE_CODE=$(curl -o /dev/null -s -w "%{http_code}" http://backend:8080/health)
            if [ "$RESPONSE_CODE" -ne 200 ]; then
              echo "ğŸš¨ API Health Check Failed! Response Code: $RESPONSE_CODE"
              exit 1
            else
              echo "âœ… API Health Check Passed! Service is running."
            fi
